apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vector-db.fullname" . }}-config
  labels:
    {{- include "vector-db.labels" . | nindent 4 }}
data:
  # Add any application configuration files here
  # For example:
  # config.json: |
  #   {
  #     "key": "value"
  #   }
  # If no config files are needed, this can be left empty 