apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vector-db.fullname" . }}-secrets
  labels:
    {{- include "vector-db.labels" . | nindent 4 }}
type: Opaque
data:
  # The values should be base64 encoded
  # You can generate them with: echo -n "your-api-key" | base64
  # In production, use Helm's secrets management or external secrets providers
  cohere-api-key: {{ .Values.secrets.cohereApiKey | default "" | b64enc | quote }} 